# Generated by Django 5.2.5 on 2025-08-23 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_payment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="purchase_date",
            new_name="payment_date",
        ),
    ]
