# Generated by Django 5.2.5 on 2025-08-26 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_rename_purchase_date_payment_payment_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
