# Generated by Django 5.2.5 on 2025-10-26 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_payment_link"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="payment_amount",
            new_name="amount_in_cents",
        ),
    ]
