# Generated by Django 5.2.5 on 2025-10-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_coursesubscribe"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                max_digits=10,
                verbose_name="Цена курса в $",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                max_digits=10,
                verbose_name="Цена урока в $",
            ),
        ),
    ]
